// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CateatetableforFilters : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CateatetableforFilters));
        
        string IMigrationMetadata.Id
        {
            get { return "201804140723024_Cateate table for Filters"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
